general:
  # root_path: ../../CIFAR100_TinyImageNet_ResNet
  # csv_name: cifar100_tinyimagenet_instances.csv
  # Following the format on https://github.com/ChristopherBrix/vnncomp2022_benchmarks
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar100_tinyimagenet_resnet
  csv_name: instances.csv
data:
  dataset: CIFAR100
  num_outputs: 100
  start: 34  # Subject to change.
  end: 58
model:
  onnx_optimization_flags: merge_bn
attack:
  pgd_order: skip
  pgd_restarts: 10
solver:
  # TODO: tune both alpha-crown and beta-crown parameters (learning rate, iterations, learning rate decay, AND batch size)
  beta-crown:
    batch_size: 256
    lr_alpha: 0.05
    lr_beta: 0.1
    iteration: 5
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: False
  prune_after_crown: True
bab:
  initial_max_domains: 100
  # TODO: tune branching heuristic parameters.
  branching:
    method: kfsb
    candidates: 7
    reduceop: max
  interm_transfer: False
