# Configuration file for running the nn2sys_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/collins_rul_cnn # https://github.com/ChristopherBrix/vnncomp2022_benchmarks/tree/main/benchmarks
  # root_path: ../../vnncomp22/benchmarks/collins  # https://github.com/loonwerks/vnncomp2022
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
data:
  dataset: Collins-rul-cnn
  num_outputs: 1
solver:
  bound_prop_method: forward+backward  # TODO try alpha-crown?
  beta-crown:
    batch_size: 100  # Number of parallel domains to compute on GPU.
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  branching:
    method: sb-fast
    input_split:
      enable: True
      enhanced_bound_prop_method: forward+backward
attack:
  pgd_order: before
  pgd_restarts: 100
