general:
  mode: verified-acc
  root_path: ../../vnncomp2022_benchmarks/benchmarks/mnist_fc
  csv_name: instances.csv
  complete_verifier: bab-refine
data:
  dataset: MNIST
  start: 30
  end: 90
solver:
  beta-crown:
    batch_size: 4096
    iteration: 20
    lr_beta: 0.03
    enable_opt_interm_bounds: True
  mip:
    parallel_solvers: 32
    solver_threads: 1
    refine_neuron_time_percentage: 0.8
  start_save_best: -1
bab:
  branching:
    candidates: 5
    reduceop: max
attack:
  attack_mode: diversed_PGD
  pgd_restarts: 100
