general:
  mode: verified-acc
  root_path: ../../vnncomp2022_benchmarks/benchmarks/mnist_fc
  csv_name: instances.csv
  complete_verifier: mip
data:
  dataset: MNIST
  start: 0
  end: 30
solver:
  beta-crown:
    batch_size: 500
    iteration: 20
    lr_beta: 0.03
  mip:
    parallel_solvers: 8
    solver_threads: 4
    refine_neuron_time_percentage: 0.8
bab:
  branching:
    candidates: 5
    reduceop: max
