# Configuration file for running the nn2sys_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/nn4sys
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
data:
  dataset: NN4SYS_2022
  num_outputs: 1
  start: 85
solver:
  bound_prop_method: forward+backward
  beta-crown:
    batch_size: 256  # Number of parallel domains to compute on GPU.
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  initial_max_domains: 1000
  branching:
    method: sb-fast  # Split on input space.
    sb_coeff_thresh: 0.1
    input_split:
      enable: True
      adv_check: .inf
attack:
  pgd_order: skip
