general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/reach_prob_density/
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
data:
  dataset: Reach_probability
solver:
  bound_prop_method: forward+backward
  beta-crown:
    batch_size: 8192  # Number of parallel domains to compute on GPU.
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  branching:
    method: sb-fast
    input_split:
      enable: True
attack:
  pgd_order: skip
