general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar100_tinyimagenet_resnet
  csv_name: instances.csv
data:
  dataset: TinyImageNet
  num_outputs: 200
  start: 74  # Subject to change.
  end: 98
model:
  onnx_optimization_flags: merge_bn
attack:
  pgd_order: skip
  pgd_restarts: 10
solver:
  # TODO: tune both alpha-crown and beta-crown parameters (learning rate, iterations, learning rate decay, AND batch size)
  beta-crown:
    batch_size: 256
    lr_alpha: 0.05
    lr_beta: 0.1
    iteration: 5
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
bab:
  # TODO: tune branching heuristic parameters.
  initial_max_domains: 10000
  branching:
    method: kfsb
    candidates: 7
    reduceop: max
  interm_transfer: False
