# Configuration file for running the nn2sys_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/tllverifybench
  csv_name: instances.csv
  enable_incomplete_verification: False
  conv_mode: matrix
data:
  dataset: TLLVerifyBench
  num_outputs: 1
model:
  onnx_optimization_flags: merge_linear
solver:
  bound_prop_method: forward+backward
  beta-crown:
    batch_size: 100  # Number of parallel domains to compute on GPU.
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  branching:
    method: naive
    input_split:
      enable: True
attack:
  pgd_order: before
