# Configuration file for running the nn2sys_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/vggnet16_2022
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
data:
  dataset: ImageNet
  num_outputs: 1000
solver:
  bound_prop_method: forward+backward
  forward:
    dynamic: True
    max_dim: 100
  beta-crown:
    batch_size: 1  # Number of parallel domains to compute on GPU.
    iteration: 10  # Iterations for computing intermediate layer bounds.
  crown:
    batch_size: 16
bab:
  branching:
    method: sb-fast
    input_split:
      enable: True
attack:
  pgd_order: skip
  check_clean: True
